swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger TokyoTravel"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:4200"
basePath: "/"
tags:
  - name: "auth"
    description: "Oauth2により認証を行う"
  - name: "adTop"
    description: "Administration Topページにおけるデータ通信定義"
  - name: "adChart"
    description: "Administration Chartページにおけるデータ通信定義"
  - name: "adEvent"
    description: "Administration Eventページにおけるデータ通信定義"
  - name: "adSpot"
    description: "Administration Spotページにおけるデータ通信定義"
  - name: "cpCalendar"
    description: "Content Calendarページにおけるデータ通信定義"
  - name: "cpTop"
    description: "Content Topページにおけるデータ通信定義"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
  - name: "global"
    description: "Webサイトの特定のページに該当しない処理連携"
  
schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /auth/facebook:
    get:
      tags:
      - "auth"
      summary: "Facebook認証"
      description: "Facebookにより認証情報を取得する"
      operationId: "getUserProfileWithFacebook"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"
          
  /auth/github:
    get:
      tags:
      - "auth"
      summary: "github認証"
      description: "githubにより認証情報を取得する"
      operationId: "getUserProfileWithGithub"
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"

  /adTop/treeMenu:
    get:
      tags:
      - "adTop"
      - "cpTop"
      summary: "Administration Topページ、もしくはTopページにおいてTreeMenuを取得する"
      operationId: "readTreeMenu"
      responses:
        200:
           description: "successful operation return json menu data"
        400:
          description: "Invalid status value"
          
  /adTop/publish:
    get:
      tags:
      - "adTop"
      summary: "Administration TopページにおいてPublish情報を取得する"
      operationId: "readPublishInfo"
      responses:
        200:
          $ref: '#/responses/publishArray'
        400:
          description: "Invalid status value"
    post:
      tags:
      - "adTop"
      summary: "Administration Topページにおいて、記事を登録する"
      operationId: "createPublishInfo"
      parameters:
        - $ref: '#/parameters/publish'
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"
    put:
      tags:
      - "adTop"
      summary: "Administration Topページにおいて、TRN_PUBLISHテーブルのデータを修正する"
      operationId: "modifyPublish"
      parameters:
        - $ref: '#/parameters/publishArray'
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"

  /adChart:
    get:
      tags:
      - "adChart"
      summary: "Chartのテンプレート情報を取得"
      operationId: "readChartTemplate"
      responses:
        200:
          $ref: '#/responses/chart'
        400:
          description: "Invalid status value"
    post:
      tags:
      - "adChart"
      summary: "chartのテンプレート情報を新規追加"
      operationId: "createChartTemplate"
      parameters:
        - $ref: '#/parameters/chart'
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid input"

  /adEvent/research:
    get:
      tags:
      - "adEvent"
      summary: "Event Research情報の取得"
      operationId: "readEventResearch"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/EventResearch"
        400:
          description: "Invalid status value"
    put:
      tags:
      - "adEvent"
      summary: "Event Research情報の更新を行う"
      operationId: "updateEventResearch"
      parameters:
        - $ref: '#/parameters/eventResearch'
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"
    post:
      tags:
      - "adEvent"
      summary: "Event Research情報の新規追加"
      operationId: "createEventResearch"
      parameters:
        - $ref: '#/parameters/eventResearch'
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"

  /adEvent/event:
    get:
      tags:
      - "adEvent"
      summary: "Event情報の取得"
      operationId: "readEvent"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/event"
        400:
          description: "Invalid status value"
    put:
      tags:
      - "adEvent"
      summary: "Event 情報の更新"
      operationId: "updateEvent"
      parameters:
        - $ref: '#/parameters/event'
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/event"
        400:
          description: "Invalid status value"
    post:
      tags:
      - "adEvent"
      summary: "Event 情報の新規追加"
      operationId: "createEvent"
      parameters:
        - $ref: '#/parameters/event'
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
  /adSpot:
    get:
      tags:
      - "adSpot"
      summary: "Chartのテンプレート情報を取得"
      operationId: "readSpot"
      responses:
        200:
          $ref: '#/responses/spotArray'
        400:
          description: "Invalid status value"

  
  /cpCalendar/calendar:
    get:
      tags:
      - "cpCalendar"
      summary: "Calendarに出力するEvent情報を取得する"
      operationId: "getEventCalendar"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/event"
        400:
          description: "Invalid status value"

  /cpTop/chart/{chartDate}:
    get:
      tags:
      - "cpTop"
      summary: "Topページに出力するBasic Lineチャート用のデータを取得する"
      operationId: "readMonthlyChart"
      parameters:
        - $ref: '#/parameters/chartDate'
      responses:
        200:
          description: "Chartデータ用のJSON文字列を返却"
        400:
          description: "Invalid status value"
  /cpTop/publish:
    get:
      tags:
      - "cpTop"
      summary: "Topページに出力する記事情報を画面のパラメーターから取得する"
      operationId: "readPublish"
      parameters:
        - $ref: '#/parameters/publish'
      responses:
        200:
          $ref: "#/responses/publish"
        400:
          description: "Invalid status value"
  /cpTop/publish/latest:
    get:
      tags:
      - "cpTop"
      summary: "Topページに出力する最新記事を取得する"
      operationId: "readPublishLatest"
      responses:
        200:
          $ref: "#/responses/publish"
        400:
          description: "Invalid status value"

  /global/user:
    get:
      tags: 
      - "global"
      summary: "User情報を取得する"
      operationId: "getUserInfo"
      parameters:
        - $ref: '#/parameters/bearerAuth'
      responses:
        200:
          description: "正常応答"
          schema:
            $ref: '#/definitions/timeline'
        400:
          description: "Invalid status value"
          
  /global/user/timeline:
    get:
      tags: 
      - "global"
      summary: "UserのTimelineデータを取得する"
      operationId: "geTimeLine"
      parameters:
        - $ref: '#/parameters/bearerAuth'
      responses:
        200:
          description: "正常応答"
          schema:
            type: array
            items:
              $ref: '#/definitions/timeline'
        400:
          description: "Invalid status value"
    put:
      tags:
      - "global"
      summary: "ダイアログで出力されたイベント情報のStarがON/OFFになった際に、その状態を保存する"
      operationId: "putTimeline"
      parameters:
        - $ref: '#/parameters/bearerAuth'
        - $ref: '#/parameters/timeLine'
      responses:
        200:
          description: "正常応答"
          schema:
            type: "string"
            description: "ファイルパス"
        400:
          description: "Invalid status value"
          
  /global/storage:
    post:
      tags: 
        - "global"
      summary: "Session Storageにため込んでいる情報をELKに登録する"
      operationId: "sStorageDataToServer"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/sessionStorage"
      responses:
        200:
          description: "成功時レスポンス"
        400:
          description: "Invalid status value"


responses:
  chart:
    description: "successful operation"
    schema:
      type: "array"
      items:
        $ref: "#/definitions/chart"
  chartDate:
    description: "chart出力対象のJsonデータ"
    schema:
      type: "string"
  publish:
    description: "successful operation"
    schema:
      $ref: "#/definitions/publish"
  publishArray:
    description: "successful operation"
    schema:
      type: "array"
      items:
        $ref: "#/definitions/publish"
  spotArray:
    description: "successful operation"
    schema:
      type: "array"
      items:
        $ref: "#/definitions/spot"


parameters:
  bearerAuth:
    name: Authorization
    description: bearer <JWT token>
    required: true
    in: header
    type: string
  chart:
    name: chart
    description: "chartのtemplateデータ"
    required: true
    in: body
    schema:
      type: "array"
      items:
        $ref: "#/definitions/chart"
  chartDate:
    name: chartDate
    description: "chart出力対象の日付"
    required: true
    in: path
    type: "string"
  event:
    name: event
    description: "Eventデータ"
    required: true
    in: body
    schema:
      type: "array"
      items:
        $ref: "#/definitions/event"
  eventResearch:
    name: eventResearch
    description: "Event Researchデータ"
    required: true
    in: body
    schema:
      type: "array"
      items:
        $ref: "#/definitions/EventResearch"
  publish:
    name: publish
    description: "月単位のchart情報"
    required: true
    in: body
    schema:
      $ref: '#/definitions/publish'
  publishArray:
    name: publishArray
    description: "配列単位の月単位のchart情報"
    required: true
    in: body
    schema:
      type: "array"
      items:
        $ref: "#/definitions/publish"
  publishDate:
    name: publishDate
    description: "記事を作成した時刻"
    required: true
    in: path
    type: "number"
  timeLine:
    name: timeLine
    description: "Userテーブルに格納されているtimelineのJsonの型"
    required: true
    in: body
    schema:
      $ref: '#/definitions/timeline'

definitions:
  chart:
    type: "object"
    properties:
      chart_name:
        type: "string"
        description: "チャートの名称"
      chart_lib:
        type: "string"
        description: "使用するチャートのライブラリー"
      target:
        type: "boolean"
        description: "クライアントのみで使用しサーバー側では使用しない"
      chart_date:
        type: "string"
        description: "チャートの出力対象日付"
      chart_value:
        type: "string"
        description: "チャート出力用データ"
      addDate:
        type: "string"
        format: "yyyyMMdd"
      modDate:
        type: "string"
        format: "yyyyMMdd"
      delete_flg:
        type: "integer"
        format: "int32"
  event:
    type: "object"
    properties:
      researchNumber:
        type: "string"
        format: "ID , sequential"
      eventNumber:
        type: "string"
        format: "ID , sequential"
      domainIcon:
        type: "string"
        description: "ドメインのFabicon"
      target:
        type: "boolean"
        description: "クライアントのみで使用しサーバー側では使用しない"
      eventUrl:
        type: "string"
        format: "URL"
      eventPdf:
        type: "string"
        description: "Eventの詳細を記載したPDF"
      eventCategory:
        type: "string"
        description: "Eventのカテゴリー"
        enum:
        - "Digital Art"
        - "Ramen"
      eventTitle:
        type: "string"
        description: "Eventの名前"
      eventYear:
        type: "string"
        format: "yyyy"
      eventStartDate:
        type: "string"
        format: "yyyyMMdd"
      eventEndDate:
        type: "string"
        format: "yyyyMMdd"
      eventSpanType:
        type: integer
        format: int32
        enum:
          - 1
          - 2
          - 3
        x-enumNames:
          - OneDay
          - Period
          - AllTime 
      district:
        type: "string"
        description: "Eventの開催場所"
        enum:
        - "Shinjuku"
      longitude:
        type: "integer"
        format: "Double"
        description: "Event開催場所の経度"
      latitude:
        type: "integer"
        format: "Double"
        description: "Event開催場所の緯度"
      color:
        type: "string"
        description: "表示の色"
        enum:
        - "blue"
        - "black"
      addDate:
        type: "string"
        format: "yyyyMMdd"
      modDate:
        type: "string"
        format: "yyyyMMdd"
      deleteFlg:
        type: "integer"
        format: "int32"
  EventResearch:
    type: "object"
    properties:
      researchNumber:
        type: "string"
        format: "sequential"
      eventNumber:
        type: "string"
        format: "sequential"
      researchWord:
        type: "string"
        description: "Google検索文言"
      research_domain:
        type: "string"
        format: "URL"
      domainIcon:
        type: "string"
        description: "ドメインのFabicon"
      rTarget:
        type: "boolean"
        description: "Researchデータ追加・修正フラグ、クライアントのみで使用しサーバー側では使用しない"
      eTarget:
        type: "boolean"
        description: "Eventデータ追加フラグ、クライアントのみで使用しサーバー側では使用しない"
      siteCategory:
        type: "string"
        description: "リサーチ用サイトのカテゴリ"
        enum:
        - "Amusement"
        - "Culture"
        - "Food"
        - "Organization"
        - "Publisher"
        - "Retail"
        - "Twitter"
      eventUrl:
        type: "string"
        description: "Research画面からEventデータを生成する際に使用する"        
        format: "URL"
      eventCategory:
        type: "string"
        description: "Research画面からEventデータを生成する際に使用する 、埋め込むときに修正が必要"        
      addDate:
        type: "string"
        format: "yyyyMMdd"
      modDate:
        type: "string"
        format: "yyyyMMdd"
      deleteFlg:
        type: "integer"
        format: "int32"
  publish:
    type: "object"
    properties:
      publishType:
        type: "string"
        description: "ユーザーに伝達する情報の種類を定義"
      publishName:
        type: "string"
        description: "ユーザーに伝達する際の情報名"
      publishDate:
        type: "number"
        description: "伝達する情報の発行日付"
      publishTitle:
        type: "string"
        description: "伝達する情報のタイトル"
      publishText:
        type: "string"
        description: "伝達する情報の中身"
      target:
        type: "boolean"
        description: "クライアントのみで使用しサーバー側では使用しない"
      isLatestToward:
        type: "boolean"
        description: "クライアントのみで使用しサーバー側では使用しない"
      addDate:
        type: "string"
        format: "yyyyMMdd"
      modDate:
        type: "string"
        format: "yyyyMMdd"
      latest_flg:
        type: "integer"
        format: "int32"
      last_flg:
        type: "integer"
        format: "int32"
      delete_flg:
        type: "integer"
        format: "int32"
  sessionStorage:
    type: "object"
    properties:
      id:
        type: "string"
      dateTime:
        type: "string"
      temporary:
        type: "boolean"
      tokenID:
        type: "string"
      food:
        type: "object"
        properties:
          ramen:
            type: "number"
      org:
        type: "object"
        properties:
          degitalArt:
            type: "number"
  spot:
    type: "object"
    properties:
      spot_name:
        type: "string"
        description: "観光目的を持つ場所の名前"
      spot_address:
        type: "string"
        description: "観光目的を持つ場所の住所"
      spot_category:
        type: "number"
        description: "観光目的を持つ場所の種別"
      spot_title:
        type: "string"
        description: "カード情報に出力する為のタイトル"
      spot_sub_title:
        type: "string"
        description: "カード情報に出力する為のサブタイトル"
      spot_picture_header:
        type: "string"
        description: "カード情報に出力する為のヘッダーの写真"
      spot_picture_main:
        type: "number"
        description: "カード情報に出力する為のメインの写真"
      spot_description:
        type: "string"
        description: "カード情報に出力する為のメイン情報"
      spot_pdf:
        type: "string"
        description: "カード情報から詳細を情報を出力するPDFのパス"
      spot_ward:
        type: "string"
        description: "観光目的を持つ場所の所在地区"
      spot_latitude:
        type: "string"
        description: "観光目的を持つ場所の経度"
      spot_longitude:
        type: "string"
        description: "観光目的を持つ場所の緯度"
      zoom:
        type: "number"
        description: "Google Mapのzoom度"
      target:
        type: "boolean"
        description: "クライアントのみで使用しサーバー側では使用しない"
      addDate:
        type: "string"
        format: "yyyyMMdd"
      modDate:
        type: "string"
        format: "yyyyMMdd"
      delete_flg:
        type: "integer"
        format: "int32"
            
  timeline:
    type: "object"
    properties:
      id:
        type: "string"
      start:
        type: "string"
      end:
        type: "string"
      name:
        type: "string"
      move:
        type: "string"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"