swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger TokyoTravel"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:4200"
basePath: "/"
tags:
  - name: "globalNos"
    description: "Webサイトの特定のページに該当しない処理連携、Redisとの連携を行う"
  - name: "globalTrn"
    description: "Webサイトの特定のページに該当しない処理連携、MARIADBとの連携を行う"
  
schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:

  /nosMovieTimeline/uuidMovie/{param}:
    get:
      tags:
      - "globalNos"
      summary: "TRN_MOVIEの「UUID」を使用して、NOS_MOVIE_TIMELINEから該当するデータを取得する"
      operationId: "readNosMovieTimeline"
      parameters:
        - $ref: '#/parameters/param'
      responses:
        200:
          $ref: '#/responses/nosMovieTimeline'
        400:
          description: "Invalid status value"
    post:
      tags: 
      - "globalNos"
      summary: "TRN_MOVIEのUUIDを引数に渡し、その情報に紐づくOver View情報を生成する。リクエストはRest Serverが受取るが、実際の処理はAccumulate Serverが行う"
      operationId: "createNosMovieTimeline"
      parameters:
        - $ref: '#/parameters/param'
      responses:
        201:
           description: "successful operation(Data was created)"
        400:
          description: "Invalid status value"
  /nosWordgraph/uuidWordgraph/{param}:
    get:
      tags:
      - "globalNos"
      summary: "TRN_WORDGRAPHの「UUID」を使用して、NOS_WORDGRAPHから該当するデータを取得する"
      operationId: "readNosWordgraphFindByuuidWordgraph"
      parameters:
        - $ref: '#/parameters/param'
      responses:
        200:
          $ref: '#/responses/nosWordgraph'
        400:
          description: "Invalid status value"
    post:
      tags: 
      - "globalNos"
      summary: "TRN_WORDGRAPHのUUIDを引数に渡し、その情報に紐づくOver View情報を生成する。リクエストはRest Serverが受取るが、実際の処理はAccumulate Serverが行う"
      operationId: "createNosWordgraph"
      parameters:
        - $ref: '#/parameters/param'
      responses:
        201:
           description: "successful operation(Data was created)"
        400:
          description: "Invalid status value"
  /nosWordgraph/searchWord/{param}:
    get:
      tags:
      - "globalNos"
      summary: "EditorConst内で保持している「searchWord」を使用して、NOS_WORDGRAPHから該当するデータを取得する、searchWordは(TRN_WORDGRAPHと値が同期する事が前提)"
      operationId: "readNosWordgraphFindBySearchWord"
      parameters:
        - $ref: '#/parameters/param'
      responses:
        200:
          $ref: '#/responses/nosWordgraph'
        400:
          description: "Invalid status value"


  /trnReference:
    get:
      tags:
      - "globalTrn"
      summary: "TRN_REFERENCEからデータを全件取得する"
      operationId: "readTrnReference"
      responses:
        200:
          $ref: '#/responses/trnReferenceArray'
        400:
          description: "Invalid status value"
    post:
      tags:
      - "globalTrn"
      summary: "TRN_REFERENCEに新規データを登録する"
      operationId: "createTrnReference"
      parameters:
        - $ref: '#/parameters/trnReferenceArray'
      responses:
        200:
          description: "successful operation"
        405:
          description: "Invalid input"
    put:
      tags:
      - "globalTrn"
      summary: "TRN_REFERENCE情報の更新を行う"
      operationId: "updateTrnReference"
      parameters:
        - $ref: '#/parameters/trnReferenceArray'
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid status value"

parameters:
  param:
    name: param
    description: "単一パラメータ用項目、UUID検索用パラメーター"
    required: true
    in: path
    type: "string"
  trnReferenceArray:
    name: trnReferenceArray
    description: "配列単位の参照情報"
    required: true
    in: body
    schema:
      type: "array"
      items:
        $ref: "#/definitions/trnReference"

responses:
  nosMovieTimeline:
    description: "successful operation"
    schema:
      $ref: "#/definitions/nosMovieTimeline"
        
  nosWordgraph:
    description: "successful operation"
    schema:
      $ref: "#/definitions/nosWordgraph"

  trnReferenceArray:
    description: "successful operation"
    schema:
      type: "array"
      items:
        $ref: "#/definitions/trnReference"

definitions:

  nosMovieTimeline:
    type: "object"
    description: "TRN_MOVIE系テーブルの集約データ格納オブジェクト、TRN_MOVIEの「Get OverView」行を押下した際、Redisからデータを取得する"
    properties:
      uuid:
        type: "string"
        description: "TRN_MOVIE_CASTからデータを取得する為のuuid情報"
      title:
        type: "string"
        description: "セットしている情報は「uuid」と一緒だが、サーバーで検索用のフィールドとして使用している"
      events:
        type: array
        items:
          type: object            
          properties:
            id:
              type: "string"
              description: "VIS timeline用のID"
            start:
              type: "string"
              description: "VIS timeline用の表示順番用値"
            end:
              type: "string"
              description: "VIS timeline用の表示順番用値"
            group:
              type: "string"
              description: "VIS timeline用の表示用ラベル"
            content:
              type: "string"
              description: "VIS timeline用の表示順番用値"
            className:
              type: "string"
              description: "VIS timeline用の表示用ラベル"
      groups:
        type: array
        items:
          type: object            
          properties:
            id:
              type: "string"
              description: "VIS timeline用のID"
            content:
              type: "string"
              description: "VIS timeline用の表示用ラベル"
            className:
              type: "string"
              description: "VIS timeline用の表示用ラベル"
            value:
              type: "number"
              description: "VIS timeline用の表示順番用値"
              
  nosWordgraph:
    type: "object"
    description: "TRN_MOVIE系テーブルの集約データ格納オブジェクト、TRN_MOVIEの「Get OverView」行を押下した際、Redisからデータを取得する"
    properties:
      uuid:
        type: "string"
        description: "TRN_MOVIE_CASTからデータを取得する為のuuid情報"
      searchWord:
        type: "string"
        description: "Editorからボタン経由でネットワークグラフを表示する際に使用するフィールド"
      title:
        type: "string"
        description: "セットしている情報は「uuid」と一緒だが、サーバーで検索用のフィールドとして使用している"
      edges:
        type: array
        items:
          type: object            
          properties:
            from:
              type: "string"
              description: "VIS network用のID"
            to:
              type: "string"
              description: "VIS network用の表示用ラベル"
            length:
              type: "string"
              description: "VIS network用の表示用ラベル"
            width:
              type: "string"
              description: "VIS network用の表示順番用値"
            value:
              type: "string"
              description: "VIS network用の表示順番用値"
      label:
        type: array
        items:
          type: object            
          properties:
            id:
              type: "string"
              description: "VIS network用のID"
            x:
              type: "string"
              description: "VIS network用のX座標"
            y:
              type: "string"
              description: "VIS network用のY座標"
            label:
              type: "string"
              description: "VIS network用のラベル"
            group:
              type: "string"
              description: "VIS network用のグループ"
            fixed:
              type: "string"
              description: "VIS network用のプロパティー、「false」を設定"
            physics:
              type: "string"
              description: "VIS network用のプロパティー、「false」を設定"
            uuid:
              type: "string"
              description: "TRN_WORDGRAPH_LABLEのUUID"
      nodes:
        type: array
        items:
          type: object            
          properties:
            id:
              type: "string"
              description: "VIS network用のID"
            label:
              type: "string"
              description: "VIS network用の表示用ラベル"
            group:
              type: "string"
              description: "VIS network用の表示用グループ"
            value:
              type: "number"
              description: "VIS network用の表示順番用値"
            uuid:
              type: "string"
              description: "TRN_WORDGRAPH_NODESのUUID"

  trnReference:
    type: "object"
    properties:
      uuid:
        type: "string"
        description: "TRN_REFERENCEのUUID"
      name:
        type: "string"
        description: "参照情報の名称"
      content_type:
        type: "string"
        description: "参照情報の中身の種類"
      platform_type:
        type: "string"
        description: "参照情報の発信媒体"
      domain:
        type: "string"
        description: "参照情報のURL"
      url:
        type: "string"
        description: ""
      memo:
        type: "string"
        description: "備考"
      target:
        type: "boolean"
        description: "クライアントのみで使用しサーバー側では使用しない"
      addDate:
        type: "string"
        format: "yyyyMMdd"
      modDate:
        type: "string"
        format: "yyyyMMdd"
      delete_flg:
        type: "integer"
        format: "int32"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"